# Generated by Django 4.2.18 on 2025-11-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='item_catego_name_6c02f0_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_sold', 'created_at'], name='item_item_is_sold_24e750_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category', 'is_sold'], name='item_item_categor_a13802_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['created_by', 'created_at'], name='item_item_created_884210_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_sold', 'category', 'created_at'], name='item_item_is_sold_745da5_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name'], name='item_item_name_a28963_idx'),
        ),
    ]
