# Generated by Django 4.2.18 on 2025-11-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-modified_at'], name='conversatio_modifie_94e719_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['item', '-modified_at'], name='conversatio_item_id_3fde51_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['created_at'], name='conversatio_created_e735e8_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='conversatio_convers_4d83d4_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['created_by', 'created_at'], name='conversatio_created_736877_idx'),
        ),
    ]
